oxGwt/pom.xml, oxLdap-annotations/pom.xml, oxLdap/pom.xml, oxSaml/pom.xml, oxService/pom.xml, oxService/src/main/java/org/xdi/config/oxtrust/LdapOxAuthConfiguration.java, oxUtil/pom.xml, pom.xml
issues:40 Json Editor Configurations
=> Json editor

oxService/pom.xml, oxService/src/main/java/org/xdi/service/ExternalResourceHandler.java, pom.xml
This pull request related with [this issue](https://github.com/GluuFederation/oxAuth/pull/392)
- moved ExternalResourceHandler from oxAuth and oxTrust
- added possibility to load custom *.page.xml files
=> oxAuth. Issue: 365

oxService/src/main/java/org/xdi/service/ExternalResourceHandler.java
This pull request is related with [this one](https://github.com/GluuFederation/community-edition-setup/pull/233).
=> - changed path to external resource directory

oxService/src/main/java/org/xdi/service/batch/BatchService.java
Related with [this pull request](https://github.com/GluuFederation/oxAuth/pull/424)
=> oxAuth. Issue 419

oxServer/src/main/java/org/gluu/oxserver/filters/AbstractCorsFilter.java
CORS filter doesn't seem to process pre-flight requests in CE 3.1.x
=> oxAuth #542 CORS_Filter_CE-3.1.x

oxLdap/src/main/java/org/gluu/site/ldap/OperationsFacade.java
=> Fixed 'paged results cookie is invalid' exception

oxLdap/src/main/java/org/gluu/site/ldap/persistence/AbstractEntryManager.java
Fix update with empty list
Support bean properties with empty list #26
=> Cover empty lists in update operations

oxLdap/src/main/java/org/gluu/site/ldap/OperationsFacade.java, oxLdap/src/main/java/org/gluu/site/ldap/persistence/LdapEntryManager.java
Updated to handle IndexOutofBound and NullPointerExceptions
=> oxTrust#643

oxService/src/main/java/org/xdi/config/oxtrust/ImportPersonConfig.java
Related with [this issue](https://github.com/GluuFederation/oxTrust/issues/651).
=> - fixed ambiguous dependencies for type ImportPersonConfig

oxService/src/main/java/org/xdi/config/oxtrust/LdapOxTrustConfiguration.java
=> add oxTrustAttributeResolver property

oxService/src/main/java/org/xdi/model/custom/script/model/CustomScript.java, oxService/src/main/java/org/xdi/service/custom/script/CustomScriptManager.java, oxUtil/src/main/java/org/xdi/model/SimpleExtendedCustomProperty.java
Created Class SimpleExtendedCustomProperty.
=> oxTrust#424

oxService/src/main/java/org/xdi/config/oxtrust/AppConfiguration.java
added authenticationRecaptchaEnabled on manage authentication page.
=> https://github.com/GluuFederation/oxTrust/issues/1072 : added authenticationRecaptchaEnabled on manage authentication page.

oxService/pom.xml, oxService/src/main/java/org/xdi/service/custom/script/AbstractCustomScriptService.java, pom.xml
Added method in AbstractCustomScriptService to facilitate script searching based on INUMs. Clients can get the script data without sending the complete DN in requests.
=> INum based search support for LDAP

oxPersist/src/main/java/org/gluu/persist/PersistenceEntryManager.java, oxPersist/src/main/java/org/gluu/persist/impl/BaseEntryManager.java, oxService/src/main/java/org/xdi/model/passport/ProviderDetails.java
=> small refactoring

.gitignore, oxRadius/pom.xml, oxRadius/src/main/java/org/gluu/radius/model/RadiusClient.java, oxRadius/src/main/java/org/gluu/radius/model/ServerConfiguration.java, pom.xml
* Added oxRadius to the 4.0 Milestone
* Adjusted oxRadius code to conform the new persistence abstraction layer
=> Pull request from Rolain Djeumen

oxService/src/main/java/org/gluu/config/oxtrust/AppConfiguration.java
Added oxTrust json properties needed for Fapi implementation in oxTrust module.
```
1. oxAuthClientFapiJWKPrivateKeyModulus
2. oxAuthClientFapiJWKPrivateKeyPrivateExponent
3. oxAuthFapiClientKeystoreType
4. oxAuthFapiClientKeystorePath
5. oxAuthFapiClientKeystorePassword
```
=> Ox trust/issues/1924

oxModel/src/main/java/org/gluu/model/types/LoggingLayoutType.java, oxService/src/main/java/org/gluu/service/logger/LoggerService.java
Added methods to add new appenders using the layout configured in a json property.
=> JsonLayout for logs. oxAuth/issue #1308

oxService/src/main/java/org/gluu/service/cdi/event/CibaRequestsProcessorEvent.java
GluuFederation/oxAuth/issues/1361
=> Ciba requests processor event. 

core-cache/src/main/java/org/gluu/service/cache/RedisSentinelProvider.java
`Set.of` is not compatible with Java 8.
=> Compability with java 8 for Sets

core-cache/src/main/java/org/gluu/service/cache/RedisClusterProvider.java, core-cache/src/main/java/org/gluu/service/cache/RedisConfiguration.java, core-cache/src/main/java/org/gluu/service/cache/RedisProviderFactory.java, core-cache/src/main/java/org/gluu/service/cache/RedisSentinelProvider.java, core-cache/src/main/java/org/gluu/service/cache/RedisSetParams.java, core-cache/src/main/java/org/gluu/service/cache/RedisShardedProvider.java, core-cache/src/main/java/org/gluu/service/cache/RedisStandaloneProvider.java
Issue: https://github.com/GluuFederation/oxCore/issues/215
Related PRs:
- https://github.com/GluuFederation/oxTrust/pull/2114
- https://github.com/GluuFederation/gluu-core-bom/pull/12
=> Use newer Jedis lib version 3.7.0

core-cache/src/main/java/org/gluu/service/cache/RedisClusterProvider.java, core-cache/src/main/java/org/gluu/service/cache/RedisConfiguration.java, core-cache/src/main/java/org/gluu/service/cache/RedisProviderFactory.java, core-cache/src/main/java/org/gluu/service/cache/RedisSentinelProvider.java, core-cache/src/main/java/org/gluu/service/cache/RedisSetParams.java, core-cache/src/main/java/org/gluu/service/cache/RedisShardedProvider.java, core-cache/src/main/java/org/gluu/service/cache/RedisStandaloneProvider.java
Cherry pick from https://github.com/GluuFederation/oxCore/pull/221
=> Updated Redis providers to support SSL connection

oxUtil/src/main/java/org/gluu/util/security/SecurityProviderUtility.java
* feat: security_mode_type has been added to the security_provider_utility;
* fix: comments have been removed;
* fix: unnecessary out has been removed;
=> chore: unnecessary out has been removed; (#227)

core-document-store/pom.xml, core-document-store/src/main/java/org/gluu/service/document/store/StandaloneDocumentStoreProviderFactory.java, core-document-store/src/main/java/org/gluu/service/document/store/conf/DBDocumentStoreConfiguration.java, core-document-store/src/main/java/org/gluu/service/document/store/conf/DocumentStoreConfiguration.java, core-document-store/src/main/java/org/gluu/service/document/store/conf/DocumentStoreType.java, core-document-store/src/main/java/org/gluu/service/document/store/provider/DBDocumentStoreProvider.java, core-document-store/src/main/java/org/gluu/service/document/store/service/DBDocumentService.java, core-document-store/src/main/java/org/gluu/service/document/store/service/OxDocument.java
https://github.com/GluuFederation/oxCore/issues/223
=> Dbdocumentstore

oxSaml/src/main/java/org/gluu/saml/metadata/SAMLMetadataParser.java
https://github.com/GluuFederation/oxTrust/issues/2180
=> feat: add method for saml api

oxService/src/main/java/org/gluu/config/oxtrust/AppConfiguration.java
https://github.com/GluuFederation/oxTrust/issues/2176
=> chore: remove caCertsLocation, caCertsPassphrase properties

oxService/src/main/java/org/gluu/config/oxtrust/AppConfiguration.java, oxService/src/main/java/org/gluu/model/LocaleSupported.java
https://github.com/GluuFederation/oxTrust/issues/2226
locale configurable.
=> feat: added locale in DB AppConfiguration oxtrust 2226

oxService/src/main/java/org/gluu/model/LocaleSupported.java
https://github.com/GluuFederation/oxTrust/issues/2226
=> feat: added few corrections oxtrust 2226

core-document-store/src/main/java/org/gluu/service/document/store/provider/DBDocumentStoreProvider.java, core-document-store/src/main/java/org/gluu/service/document/store/provider/DocumentStore.java, core-document-store/src/main/java/org/gluu/service/document/store/provider/JcaDocumentStoreProvider.java, core-document-store/src/main/java/org/gluu/service/document/store/provider/LocalDocumentStoreProvider.java, core-document-store/src/main/java/org/gluu/service/document/store/provider/WebDavDocumentStoreProvider.java, core-document-store/src/main/java/org/gluu/service/document/store/service/BaseDocumentStoreService.java, core-document-store/src/main/java/org/gluu/service/document/store/service/OxDocument.java, core-document-store/src/test/java/org/gluu/service/document/store/manual/JcaDocumentStoreManualTest.java, core-document-store/src/test/java/org/gluu/service/document/store/manual/WebDavDocumentStoreManualTest.java
#244  Add multiple oxmoduleProperty in Document.
=> feat : added module as multivalue #244

core-document-store/src/main/java/org/gluu/service/document/store/provider/DBDocumentStoreProvider.java
https://github.com/GluuFederation/oxTrust/issues/2258
=> fix(oxtrust-server): duplicated saml config files after restarts

oxService/src/main/java/org/gluu/config/oxtrust/AppConfiguration.java
https://github.com/GluuFederation/oxTrust/issues/2225
=> feat(oxtrust-server): remove files from ldifStore #2225

core-document-store/src/main/java/org/gluu/service/document/store/provider/DBDocumentStoreProvider.java, core-document-store/src/main/java/org/gluu/service/document/store/service/OxDocument.java
https://github.com/GluuFederation/oxTrust/issues/2256
=> fix(oxtrust-server): fix for oxEnable field oxtrust issue 2256

oxService/src/main/java/org/gluu/config/oxtrust/AppConfiguration.java, oxService/src/main/java/org/gluu/config/oxtrust/OxTrustApiMode.java
https://github.com/GluuFederation/oxTrust/issues/2260
=> feat : added oauth protection on oxtrust apis

core-document-store/src/main/java/org/gluu/service/document/store/service/OxDocument.java
fix : duplicate records in db  [#2258](https://github.com/GluuFederation/oxTrust/issues/2258)
=> fix(oxtrust): duplicated SAML config files after restarts 

core-document-store/src/main/java/org/gluu/service/document/store/provider/DBDocumentStoreProvider.java
https://github.com/GluuFederation/oxTrust/issues/2275
=> fix(oxtrust-server): format of generated Shibboleth files

oxService/src/main/java/org/gluu/config/oxtrust/AppConfiguration.java
https://github.com/GluuFederation/oxTrust/issues/2297
=> feat(oxtrust-server): changed the variable name

oxUtil/src/main/java/org/gluu/model/SmtpConnectProtectionType.java
fix: serialization/deserialization annotations have been added;
=> fix: SmtpConnectProtectionType has been updated;

core-script/src/main/java/org/gluu/model/custom/script/type/token/DummyUpdateTokenType.java, core-script/src/main/java/org/gluu/model/custom/script/type/token/UpdateTokenType.java
feat(oxcore): introduce new UpdateToken methods 
https://github.com/GluuFederation/oxAuth/issues/1728
=> feat(oxcore): introduce new UpdateToken methods

oxService/src/main/java/org/gluu/service/util/PageService.java
https://github.com/GluuFederation/oxAuth/issues/1829
=> fix(oxauth-server): on error pages currentdatetime is null

server/src/main/java/org/gluu/server/filters/AbstractCorsFilter.java
https://github.com/GluuFederation/oxAuth/issues/1854
=> fix: Authentication Filter should not process OPTIONS request method

core-document-store/src/main/java/org/gluu/service/document/store/provider/DBDocumentStoreProvider.java
https://github.com/GluuFederation/oxTrust/issues/2351
=> fix(oxtrust-server): 2351 validate TR metadata

core-script/src/main/java/org/gluu/model/custom/script/CustomScriptType.java, core-script/src/main/java/org/gluu/model/custom/script/type/authzchallenge/AuthorizationChallengeType.java, core-script/src/main/java/org/gluu/model/custom/script/type/authzchallenge/DummyAuthorizationChallengeType.java
feat(oxauth): added new authorization challenge custom script definition  #1925
https://github.com/GluuFederation/oxAuth/issues/1925
=> feat(oxauth): added new authorization challenge custom script definition  #1925
